ekf_local_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf: true
 
    odom0: /odom
    odom0_config: [false, false, false, 
                   false, false, false, 
                   true,  false,  false, 
                   false, false, false, 
                   false, false, false] 
    odom0_queue_size: 10


    # Giriş 1: IMU (/imu)
    imu0: /imu
    imu0_config: [false, false, false, # Pozisyon
                   false,  false,  true, # Roll pitch yaw
                   true, false, false,  #linear hızs
                   false,false, true, # Açısal Hız 
                   true,  false,  false] # Doğrusal İvme
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true 
    process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.06, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]


ekf_global_node:
  ros__parameters:
    frequency: 30.0 
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map 
    publish_tf: true
    odom0: /odom
    odom0_config: [false, false, false, 
                   false, false, false, 
                   true,  false,  false, 
                   false, false, false, 
                   false, false, false] 
    odom0_queue_size: 10


    imu0: /imu
    imu0_config: [false, false, false, # Pozisyon
                   false,  false,  true, # Roll pitch yaw
                   false, false, false,  #linear hız
                   false, false, false, # Açısal Hız 
                   false,  false,  false] # Doğrusal İvme

    odom1: /odometry/gps
    odom1_config: [true,  true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    
navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    
  
    gps_topic: /gps/fix      
    imu_topic: /imu     
    odom_topic: /odometry/filtered
    datum: [39.796006, 32.531563] 
    base_link_frame: base_link
    gps_frame: gps_link
    magnetic_declination_radians: 0.093 
    yaw_offset: 0.0 
    zero_altitude: true 
    broadcast_cartesian_transform: true 
    publish_filtered_gps: true
    publish_tf: true
    